version: "3.1"
services:
  client:
      image: centos:7
      volumes:
        - .:/build/
        - /tmp/demo_sqs/:/tmp/
      working_dir: /build
  localstack:
      image: localstack/localstack:1.3.1
      environment:
        SKIP_SSL_CERT_DOWNLOAD: 1
        DISABLE_EVENTS: 1
        